/**Create DB Scheme**/
CREATE DATABASE  IF NOT EXISTS `vet_clinic_system` ;
USE `vet_clinic_system`;

/** Create pet Table  **/
-- DROP TABLE IF EXISTS `PET`;
CREATE TABLE `PET` (
  `PET_ID` int(11) NOT NULL AUTO_INCREMENT,
  `OWNER_ID` int(11) DEFAULT NULL,
  `NAME` varchar(45) DEFAULT NULL,
  `GENDER` ENUM('male', 'female') NOT NULL,
  `BIRTH_DATE` date DEFAULT NULL,
  `ANIMAL_KIND` varchar(45) DEFAULT NULL,
  `PHOTO_1_URL` varchar(500) DEFAULT NULL,
  `PHOTO_2_URL` varchar(500) DEFAULT NULL,
  `PHOTO_3_URL` varchar(500) DEFAULT NULL,
  `WEIGHT` numeric DEFAULT 0,
  PRIMARY KEY (`PET_ID`),
  KEY `FK_OWNER_idx` (`OWNER_ID`),
  CONSTRAINT `FK_OWNER` FOREIGN KEY (`OWNER_ID`) 
  REFERENCES `OWNER` (`OWNER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

/** Create OWNER Table  **/
-- DROP TABLE IF EXISTS `OWNER`;
CREATE TABLE `OWNER` (
  `OWNER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(45) DEFAULT NULL,
  `GENDER` ENUM('male', 'female') NOT NULL,
  `EMAIL` varchar(45) DEFAULT NULL,
  `PHONE` numeric DEFAULT NULL,
  `ADDRESS` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`OWNER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

/** Create CLINIC Table  **/
-- DROP TABLE IF EXISTS `CLINIC`;
CREATE TABLE `CLINIC` (
  `CLINIC_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(45) DEFAULT NULL,
  `WORKING_DAYS_AND_HOURS` varchar(500) DEFAULT NULL,
  `PHONE` numeric DEFAULT NULL,
  `EMAIL` varchar(45) DEFAULT NULL,
  `ADDRESS` varchar(500) DEFAULT NULL,
  `SOCIAL_NETWORK_URLS` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`CLINIC_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

/** Create DOCTOR Table  **/
-- DROP TABLE IF EXISTS `DOCTOR`;
CREATE TABLE `DOCTOR` (
  `DOCTOR_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CLINIC_ID` int(11) DEFAULT NULL,
  `NAME` varchar(45) DEFAULT NULL,
  `PHONE` numeric DEFAULT NULL,
  `PHOTO_URL` varchar(500) DEFAULT NULL,
  `BIO` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`DOCTOR_ID`),
  KEY `FK_CLINIC_idx` (`CLINIC_ID`),
  CONSTRAINT `FK_CLINIC` FOREIGN KEY (`CLINIC_ID`) 
  REFERENCES `CLINIC` (`CLINIC_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

/** Create VISIT Table  **/
-- DROP TABLE IF EXISTS `VISIT`;
CREATE TABLE `VISIT` (
  `VISIT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DOCTOR_ID` int(11) DEFAULT NULL,
  `CLINIC_ID` int(11) DEFAULT NULL,
  `PET_ID` int(11) DEFAULT NULL,
  `DATE`date DEFAULT NULL,
  PRIMARY KEY (`VISIT_ID`),
  KEY `FK_DOCTOR_VISIT_idx` (`DOCTOR_ID`),
  CONSTRAINT `FK_DOCTOR_VISIT` FOREIGN KEY (`DOCTOR_ID`) 
  REFERENCES `DOCTOR` (`DOCTOR_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  KEY `FK_CLINIC_VISIT_idx` (`CLINIC_ID`),
  CONSTRAINT `FK_CLINIC_VISIT` FOREIGN KEY (`CLINIC_ID`) 
  REFERENCES `CLINIC` (`CLINIC_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  KEY `FK_PET_VISIT_idx` (`CLINIC_ID`),
  CONSTRAINT `FK_PET_VISIT` FOREIGN KEY (`PET_ID`) 
  REFERENCES `PET` (`PET_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;